org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configureondemand=true

android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34,35
android.suppressUnsupportedOptionWarnings=true

# Gradle runtime JDK for Capacitor 7
org.gradle.java.home=C:\\Program Files\\Java\\jdk-21
